on:
  pull_request:
    branches:
      - main
    types:
      - closed
  workflow_dispatch:

jobs:      
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Ckeckout
        uses: actions/checkout@v4
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v2.1.0
        with:
          dotnet-version: 6.0.100

      - name: Restore dependencies
        run: dotnet restore
      - name: Increment Version
        run: |
          current_version=$(cat WebApi/version)
          new_version=$(echo "$current_version" | awk -F. '{$NF = $NF + 1;} 1' | sed 's/ /./g')
          echo ${{ github.run_number }} > WebApi/version
          cat WebApi/version
          git config --global user.email "mateuszsobota13@gmail.com"
          git config --global user.name "Mateusz3124"
          git status
          git add WebApi/version
          git commit -m this
      
        
      - name: Build
        run: dotnet build --no-restore
      - name: Publish
        run: dotnet publish ./WebApi/WebApi.csproj -c Release -o ${{ env.DOTNET_ROOT }}/api
        
      - name: Upload artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: personsApi-artifact
          path: ${{ env.DOTNET_ROOT }}/api
      - name: Push to protected branch
        uses: CasperWA/push-protected@v2
        with:
          token: ${{ secrets.TOKEN }}
          branch: main
          unprotect_reviews: true
  deploy-dev:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Dev'
      url: ${{ steps.deploy-to-azure.outputs.webapp-url }}

    steps:
    - name: Download a Build Artifact
      uses: actions/download-artifact@v3.0.0
      with:
        name: personsApi-artifact

    - name: Azure WebApp
      id: deploy-to-azure
      uses: Azure/webapps-deploy@v2
      with:
        publish-profile: ${{ secrets.PUBLISH_PROFILE_DEV }}

  deploy-prod:
    runs-on: ubuntu-latest
    needs: deploy-dev
    environment:
      name: 'Prod'
      url: ${{ steps.deploy-to-azure.outputs.webapp-url }}

    steps:
    - name: Download a Build Artifact
      uses: actions/download-artifact@v3.0.0
      with:
        name: personsApi-artifact

    - name: Azure WebApp
      id: deploy-to-azure
      uses: Azure/webapps-deploy@v2
      with:
        publish-profile: ${{ secrets.PUBLISH_PROFILE_PROD }}


      
        
