name: Update file on PR merge
on:
  pull_request:
    branches:
      - main

jobs:
  update_date:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Amend the last commit
        run: |
          git config --global user.email "mateuszsobota13@gmail.com"
          git config --global user.name "Mateusz3124"
          git fetch origin main
          git branch -a -r
          git checkout main
          git pull
          current_version=$(cat WebApi/version)
          new_version=$(echo "$current_version" | awk -F. '{$NF = $NF + 1;} 1' | sed 's/ /./g')
          echo "$new_version" > WebApi/version
          cat WebApi/version
          git add WebApi/version
          git commit --amend -m xd
          git status
          git log
          git remote set-url origin https://Mateusz3124: ${{ secrets.TOKEN }}@github.com/Mateusz3124/MWO.git
          git push --force --no-verify
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
