name: CI

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Amend the last commit
      run: |
          current_version=$(cat WebApi/version)
          new_version=$(echo "$current_version" | awk -F. '{$NF = $NF + 1;} 1' | sed 's/ /./g')
          echo "$new_version" > WebApi/version
          cat WebApi/version
    - uses: stefanzweifel/git-auto-commit-action@v5
        
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v2.1.0
      with:
        dotnet-version: 6.0.100

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Test
      run: dotnet test
        
    - name: Publish
      run: dotnet publish ./WebApi/WebApi.csproj -c Release -o ${{ env.DOTNET_ROOT }}/api

    - name: Upload artifact
      uses: actions/upload-artifact@v3.1.0
      with:
        name: personsApi-artifact
        path: ${{ env.DOTNET_ROOT }}/api

  deploy-dev:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Dev'
      url: ${{ steps.deploy-to-azure.outputs.webapp-url }}

    steps:
    - name: Download a Build Artifact
      uses: actions/download-artifact@v3.0.0
      with:
        name: personsApi-artifact

    - name: Azure WebApp
      id: deploy-to-azure
      uses: Azure/webapps-deploy@v2
      with:
        publish-profile: ${{ secrets.PUBLISH_PROFILE_DEV }}

  deploy-prod:
    runs-on: ubuntu-latest
    needs: deploy-dev
    environment:
      name: 'Prod'
      url: ${{ steps.deploy-to-azure.outputs.webapp-url }}

    steps:
    - name: Download a Build Artifact
      uses: actions/download-artifact@v3.0.0
      with:
        name: personsApi-artifact

    - name: Azure WebApp
      id: deploy-to-azure
      uses: Azure/webapps-deploy@v2
      with:
        publish-profile: ${{ secrets.PUBLISH_PROFILE_PROD }}
